version: "2.1"
services:
  hammond:
    image: akhilrex/hammond
    container_name: hammond
    environment:
      - JWT_SECRET = somethingverystrong
    volumes:
      - /path/to/config:/config
      - /path/to/data:/assets
    ports:
      - 8080:8080
    restart: unless-stopped
